stages:
  - conformity
  - build
  - test

image: registry.dune-project.org/docker/ci/ubuntu:20.04

branch-conformity:
  stage: conformity
  script:
    - echo "$GITLAB_USER_ID"
    - if [[ $CI_COMMIT_REF_NAME =~ ^[a-zA-Z0-9]+\/exercise[0-9]+ -or $GITLAB_USER_ID -eq "spraetor" ]]; then exit 1; fi
